# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Plants_analytics
                                 A QGIS plugin
 Plants_analytics
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-05-04
        copyright            : (C) 2023 by Eugene Luchshev
        email                : dragonborn7243@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Plants_analytics class from file Plants_analytics.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Plants_analytics import Plants_analytics
    return Plants_analytics(iface)
